import "./globals.css"
import { fontVariableString } from "@/app/fonts"
import { twMerge } from "tailwind-merge"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const classes = [
    "font-sans text-white",
    "h-screen flex flex-col items-center py-20",
    "bg-gradient-to-b from-[#020024] via-[#230029] to-[#230029]",
    "container mx-auto",
  ]

  return (
    <html lang="en" className={fontVariableString}>
      <body className={twMerge(classes)}>{children}</body>
    </html>
  )
}
